sudp: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t rselva/docker-react .

script:
  - docker run -e CI=true rselva/docker-react npm test  -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-691255507802"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"